//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mladek_7BBIF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public short manNummer { get; set; }
        public Nullable<short> mitNummer { get; set; }
    
        public virtual Mitarbeiter Mitarbeiter { get; set; }
    }
}
