//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mladek_7BBIF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitarbeiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mitarbeiter()
        {
            this.Manager = new HashSet<Manager>();
        }
    
        public short mitNummer { get; set; }
        public string mVorname { get; set; }
        public string mNachname { get; set; }
        public Nullable<short> gKlasse { get; set; }
        public Nullable<short> aNummer { get; set; }
        public Nullable<short> tNummer { get; set; }
    
        public virtual Abteilung Abteilung { get; set; }
        public virtual Gehalt Gehalt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager> Manager { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
